# action.yaml
name: 'Polar Signals Continuous Profiling'
description: 'Installs Parca to continuously profile your CI/CD pipeline.'
inputs:
  ps_token:
    description: 'Polar Signals cloud token.'
    required: true
  ps_store_address:
    description: 'Polar Signals remote store address.'
    required: false
    default: 'grpc.polarsignals.com:443'
  parca_agent_version:
    description: 'Parca agent version.'
    required: false
    default: '0.19.0'
  profiling_frequency:
    description: 'The frequency at which profiling data is collected.'
    required: false
    default: 99
  profiling_duration:
    description: 'The agent profiling duration to use, cycle to send profiling data.'
    required: false
    default: '3s'
outputs:
  ps_url:
    description: 'URL of Polar Signals dashboard to view the profiles. - coming soon.'
runs:
  using: 'composite'
  steps:
    - name: Install Parca Agent
      shell: bash
      run: curl -sL https://github.com/parca-dev/parca-agent/releases/download/v${{ inputs.parca_agent_version }}/parca-agent_${{ inputs.parca_agent_version }}_`uname -s`_`uname -m`.tar.gz | tar xvfz -
    - name: Run parca agent in background
      shell: bash
      run: sudo ./parca-agent --profiling-duration=${{ inputs.profiling_duration }} --profiling-cpu-sampling-frequency=${{ inputs.profiling_frequency }} --node=github --remote-store-address=${{ inputs.ps_store_address }} --remote-store-bearer-token=${{ inputs.ps_token }} &
