name: 'Polar Signals Continuous Profiling'
description: 'Installs Parca to continuously profile your CI/CD pipeline.'
inputs:
  polarsignals_cloud_token:
    description: 'Polar Signals cloud token.'
    required: true
  store_address:
    description: 'gRPC address to send data to. Defaults to Polar Signals Cloud endpoint.'
    required: false
    default: 'grpc.polarsignals.com:443'
  parca_agent_version:
    description: 'Parca agent version.'
    required: false
    default: '0.45.0'
  profiling_frequency:
    description: 'The frequency at which profiling data is collected. Parca Agent defaults to 19, but to gather more data in CI we recommend a higher frequency.'
    required: false
    default: 99
  profiling_duration:
    description: 'The agent profiling duration to use, cycle to send profiling data.'
    required: false
    default: '3s'
  labels:
    description: 'Add labels, for example branch name, branch=main'
    required: false
    default: "ref_name=${{ github.ref_name }};workflow=${{ github.workflow }};gh_run_id=${{ github.run_id }};gh_job=${{ github.job }};gh_job_index=${{ strategy.job-index }}"
  extra_args:
    description: 'Add any further arguments to the execution of the agent.'
    required: false
  config:
    description: 'Parca agent configuration file content. If provided, this will be written to a file and passed via --config-path flag.'
    required: false
  project_uuid:
    description: 'Polar Signals Cloud project UUID for query URL generation.'
    required: true
  cloud_hostname:
    description: 'Polar Signals Cloud hostname for query URL generation.'
    required: false
    default: 'cloud.polarsignals.com'
  github_token:
    description: 'GitHub token for creating PR comments with links to profiling data.'
    required: false
    default: ${{ github.token }}
  job_name:
    description: 'Job identifier for matrix workflows (e.g., node-18, ubuntu-latest). Used to distinguish parallel jobs in PR comments.'
    required: false
    default: ''
outputs:
  profiling_url:
    description: 'The URL to the profiling data in Polar Signals Cloud.'
runs:
  using: 'node16'
  main: 'index.js'
  post: 'index.js'
